### ISSUE TITLE
DeepCC test problems

### ISSUE THREAD

**Issue by Alan-JW** [Soheil-ab/DeepCC.v1.0#2]
Hey , @Soheil-ab 

Thank you very much for your contribution to the community.
I found the following phenomena when using the deepcc,

1、DeepBBR and DeepCubic performed poorly when RTT was large(rtt>50ms).

Here are my [concrete results](https://docs.google.com/document/d/1FvwMPgBmSwonOw83gDy6Sb4DQQwtB1ULH3cNzdd2AI8/edit#heading=h.frao27ro3qib)

I would like to ask you if you encountered any of the problems I mentioned above during your previous use or testing? If so, how did you solve these problems?

Thank you very much for your answer.

**Comment by Soheil-ab** [comment]
Hey @Alan-JW 

Unfortunately, You did the tests in a wrong way (but interestingly DeepCC still performed as it should! I explain it here)!

The problem is with the definition of Target delay and meaning of "latency". The value of the "latency" that is passed to the  script/server is the one-way minimum delay of the link and "Target" is the overall target delay. 

For instance, you set latency=100ms and Target=140ms in your tests. However, that means your minRTT is 200ms and your Target delay is 140ms which is not feasible in this network! That's why DeepCC doesn't let Cubic send packets! 
As a proof-of-concept code, we deliberately didn't add any kind of safety mechanisms in the current code for shooting an error if the target is less than the minRTT, etc. But if you like you can expand the code to include these safety measures.

Hope that helps
